In [64]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

In [65]:
data = pd.read_csv('ball_by_ball_ipl.csv')
data.head()

,Unnamed: 0,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
0,0,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,1,RD Gaikwad,...,Chennai Super Kings,0,4,0,1,0,NaN,NaN,4,1
1,1,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,2,RD Gaikwad,...,Chennai Super Kings,0,4,0,2,0,NaN,NaN,0,1
2,2,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,3,RD Gaikwad,...,Chennai Super Kings,0,4,0,3,0,NaN,NaN,0,1
3,3,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,4,RD Gaikwad,...,Chennai Super Kings,0,4,0,4,0,NaN,NaN,0,1
4,4,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,5,RD Gaikwad,...,Chennai Super Kings,0,5,0,5,0,NaN,NaN,1,1

In [66]:
data.tail()

,Unnamed: 0,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
239688,239688,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,1,YK Pathan,...,Sunrisers Hyderabad,1,16,31,9,29,NaN,NaN,2,1
239689,239689,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,2,YK Pathan,...,Sunrisers Hyderabad,1,22,31,10,29,NaN,NaN,6,1
239690,239690,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,3,YK Pathan,...,Sunrisers Hyderabad,1,26,31,11,29,NaN,NaN,4,1
239691,239691,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,4,YK Pathan,...,Sunrisers Hyderabad,1,27,31,12,29,NaN,NaN,1,1
239692,239692,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,5,KS Williamson,...,Sunrisers Hyderabad,1,32,27,30,12,NaN,NaN,1,1

In [67]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239693 entries, 0 to 239692
Data columns (total 35 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Unnamed: 0               239693 non-null  int64
 1   Match ID                 239693 non-null  int64
 2   Date                     239693 non-null  object
 3   Venue                    239693 non-null  object
 4   Bat First                239693 non-null  object
 5   Bat Second               239693 non-null  object
 6   Innings                  239693 non-null  int64
 7   Over                     239693 non-null  int64
 8   Ball                     239693 non-null  int64
 9   Batter                   239693 non-null  object
 10  Non Striker              239693 non-null  object
 11  Bowler                   239693 non-null  object
 12  Batter Runs              239693 non-null  int64
 13  Extra Runs               239693 non-null  int64
 14  Runs From Ball           239693 non-null  int64
 15  Ball Rebowled            239693 non-null  int64
 16  Extra Type               239693 non-null  object
 17  Wicket                   239693 non-null  int64
 18  Method                   11827 non-null   object
 19  Player Out               11827 non-null   object
 20  Innings Runs             239693 non-null  int64
 21  Innings Wickets          239693 non-null  int64
 22  Target Score             239693 non-null  int64
 23  Runs to Get              115766 non-null  float64
 24  Balls Remaining          239693 non-null  int64
 25  Winner                   239693 non-null  object
 26  Chased Successfully      239693 non-null  int64
 27  Total Batter Runs        239693 non-null  int64
 28  Total Non Striker Runs   239693 non-null  int64
 29  Batter Balls Faced       239693 non-null  int64
 30  Non Striker Balls Faced  239693 non-null  int64
 31  Player Out Runs          11827 non-null   float64
 32  Player Out Balls Faced   11827 non-null   float64
 33  Bowler Runs Conceded     239693 non-null  int64
 34  Valid Ball               239693 non-null  int64
dtypes: float64(3), int64(21), object(11)
memory usage: 64.0+ MB

In [68]:
data.shape

(239693, 35)

In [69]:
data.columns

Index(['Unnamed: 0', 'Match ID', 'Date', 'Venue', 'Bat First', 'Bat Second',
       'Innings', 'Over', 'Ball', 'Batter', 'Non Striker', 'Bowler',
       'Batter Runs', 'Extra Runs', 'Runs From Ball', 'Ball Rebowled',
       'Extra Type', 'Wicket', 'Method', 'Player Out', 'Innings Runs',
       'Innings Wickets', 'Target Score', 'Runs to Get', 'Balls Remaining',
       'Winner', 'Chased Successfully', 'Total Batter Runs',
       'Total Non Striker Runs', 'Batter Balls Faced',
       'Non Striker Balls Faced', 'Player Out Runs', 'Player Out Balls Faced',
       'Bowler Runs Conceded', 'Valid Ball'],
      dtype='object')

In [70]:
data.drop(['Unnamed: 0', 'Match ID', 'Date'], axis=1, inplace=True)

In [71]:
data.head()

,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,Bowler,Batter Runs,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
0,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,1,RD Gaikwad,DP Conway,UT Yadav,4,...,Chennai Super Kings,0,4,0,1,0,NaN,NaN,4,1
1,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,2,RD Gaikwad,DP Conway,UT Yadav,0,...,Chennai Super Kings,0,4,0,2,0,NaN,NaN,0,1
2,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,3,RD Gaikwad,DP Conway,UT Yadav,0,...,Chennai Super Kings,0,4,0,3,0,NaN,NaN,0,1
3,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,4,RD Gaikwad,DP Conway,UT Yadav,0,...,Chennai Super Kings,0,4,0,4,0,NaN,NaN,0,1
4,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,5,RD Gaikwad,DP Conway,UT Yadav,1,...,Chennai Super Kings,0,5,0,5,0,NaN,NaN,1,1

In [72]:
data.isna().sum()

Venue                           0
Bat First                       0
Bat Second                      0
Innings                         0
Over                            0
Ball                            0
Batter                          0
Non Striker                     0
Bowler                          0
Batter Runs                     0
Extra Runs                      0
Runs From Ball                  0
Ball Rebowled                   0
Extra Type                      0
Wicket                          0
Method                     227866
Player Out                 227866
Innings Runs                    0
Innings Wickets                 0
Target Score                    0
Runs to Get                123927
Balls Remaining                 0
Winner                          0
Chased Successfully             0
Total Batter Runs               0
Total Non Striker Runs          0
Batter Balls Faced              0
Non Striker Balls Faced         0
Player Out Runs            227866
Player Out Balls Faced     227866
Bowler Runs Conceded            0
Valid Ball                      0
dtype: int64

Filling Null Values

In [73]:
data['Method'].value_counts()

Method
caught                   7296
bowled                   2051
run out                  1026
lbw                       735
caught and bowled         344
stumped                   340
retired hurt               15
hit wicket                 15
retired out                 3
obstructing the field       2
Name: count, dtype: int64

In [74]:
filler_value = data['Method'].mode()[0]
data['Method'].fillna(filler_value, inplace=True)

In [75]:
data["Player Out"].value_counts()

Player Out
RG Sharma        206
V Kohli          190
S Dhawan         185
RV Uthappa       178
KD Karthik       172
                ...
Virat Singh        1
M Ntini            1
TM Srivastava      1
AS Joseph          1
DG Nalkande        1
Name: count, Length: 602, dtype: int64

In [76]:
data['Player Out'].fillna('None', inplace=True)
data['Player Out Runs'].fillna(0, inplace=True)
data['Player Out Balls Faced'].fillna(0, inplace=True)
data['Runs to Get'].fillna(0, inplace=True)

In [77]:
data.isna().sum()

Venue                      0
Bat First                  0
Bat Second                 0
Innings                    0
Over                       0
Ball                       0
Batter                     0
Non Striker                0
Bowler                     0
Batter Runs                0
Extra Runs                 0
Runs From Ball             0
Ball Rebowled              0
Extra Type                 0
Wicket                     0
Method                     0
Player Out                 0
Innings Runs               0
Innings Wickets            0
Target Score               0
Runs to Get                0
Balls Remaining            0
Winner                     0
Chased Successfully        0
Total Batter Runs          0
Total Non Striker Runs     0
Batter Balls Faced         0
Non Striker Balls Faced    0
Player Out Runs            0
Player Out Balls Faced     0
Bowler Runs Conceded       0
Valid Ball                 0
dtype: int64

In [78]:
data.shape

(239693, 32)

In [79]:
data['Method'].value_counts()

Method
caught                   235162
bowled                     2051
run out                    1026
lbw                         735
caught and bowled           344
stumped                     340
retired hurt                 15
hit wicket                   15
retired out                   3
obstructing the field         2
Name: count, dtype: int64

In [80]:
data['Venue'].value_counts()

Venue
Wankhede Stadium                                                26567
Eden Gardens                                                    20177
MA Chidambaram Stadium                                          18042
Rajiv Gandhi International Stadium                              16662
M Chinnaswamy Stadium                                           16121
Feroz Shah Kotla                                                13887
Sawai Mansingh Stadium                                          12277
Dubai International Cricket Stadium                             10444
Dr DY Patil Sports Academy                                       8898
Maharashtra Cricket Association Stadium                          8414
Punjab Cricket Association Stadium                               8266
Sharjah Cricket Stadium                                          6672
Brabourne Stadium                                                6526
Sheikh Zayed Stadium                                             6412
Punjab Cricket Association IS Bindra Stadium                     6210
Arun Jaitley Stadium                                             5808
Narendra Modi Stadium                                            3830
Subrata Roy Sahara Stadium                                       3825
Kingsmead                                                        3643
M.Chinnaswamy Stadium                                            3443
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium              3037
SuperSport Park                                                  2866
Himachal Pradesh Cricket Association Stadium                     2660
Sardar Patel Stadium                                             2635
Saurashtra Cricket Association Stadium                           2118
Holkar Cricket Stadium                                           1965
New Wanderers Stadium                                            1940
Zayed Cricket Stadium                                            1874
Barabati Stadium                                                 1695
St George's Park                                                 1677
JSCA International Stadium Complex                               1671
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium     1465
Shaheed Veer Narayan Singh International Stadium                 1431
Newlands                                                         1272
Nehru Stadium                                                    1155
Green Park                                                        921
Vidarbha Cricket Association Stadium                              742
De Beers Diamond Oval                                             726
Buffalo Park                                                      715
Barsapara Cricket Stadium                                         504
OUTsurance Oval                                                   500
Name: count, dtype: int64

In [81]:
data['Bat First'].value_counts()

Bat First
Mumbai Indians                 30697
Chennai Super Kings            29353
Royal Challengers Bangalore    27921
Kolkata Knight Riders          25564
Kings XI Punjab                22657
Rajasthan Royals               22600
Sunrisers Hyderabad            20058
Delhi Daredevils               16108
Deccan Chargers                10335
Delhi Capitals                  7830
Punjab Kings                    6482
Pune Warriors                   4759
Gujarat Titans                  3610
Lucknow Super Giants            3471
Gujarat Lions                   3046
Rising Pune Supergiant          1960
Kochi Tuskers Kerala            1650
Rising Pune Supergiants         1592
Name: count, dtype: int64

In [82]:
data['Bat First'].replace('Delhi Daredevils', 'Delhi Capitals', inplace=True)
data['Bat First'].replace('Punjab Kings', 'Kings XI Punjab', inplace=True)

In [83]:
data['Bat First'].value_counts()

Bat First
Mumbai Indians                 30697
Chennai Super Kings            29353
Kings XI Punjab                29139
Royal Challengers Bangalore    27921
Kolkata Knight Riders          25564
Delhi Capitals                 23938
Rajasthan Royals               22600
Sunrisers Hyderabad            20058
Deccan Chargers                10335
Pune Warriors                   4759
Gujarat Titans                  3610
Lucknow Super Giants            3471
Gujarat Lions                   3046
Rising Pune Supergiant          1960
Kochi Tuskers Kerala            1650
Rising Pune Supergiants         1592
Name: count, dtype: int64

In [84]:
data['Bat Second'].value_counts()

Bat Second
Kolkata Knight Riders          29329
Mumbai Indians                 27810
Royal Challengers Bangalore    27554
Rajasthan Royals               25414
Chennai Super Kings            24052
Kings XI Punjab                21430
Delhi Daredevils               20952
Sunrisers Hyderabad            18671
Delhi Capitals                 10179
Deccan Chargers                 7738
Pune Warriors                   6078
Gujarat Titans                  4363
Gujarat Lions                   3802
Lucknow Super Giants            3666
Punjab Kings                    3638
Rising Pune Supergiant          1868
Rising Pune Supergiants         1603
Kochi Tuskers Kerala            1546
Name: count, dtype: int64

In [85]:
data['Bat Second'].replace('Delhi Daredevils', 'Delhi Capitals', inplace=True)
data['Bat Second'].replace('Punjab Kings', 'Kings XI Punjab', inplace=True)

In [86]:
data['Bat Second'].value_counts()

Bat Second
Delhi Capitals                 31131
Kolkata Knight Riders          29329
Mumbai Indians                 27810
Royal Challengers Bangalore    27554
Rajasthan Royals               25414
Kings XI Punjab                25068
Chennai Super Kings            24052
Sunrisers Hyderabad            18671
Deccan Chargers                 7738
Pune Warriors                   6078
Gujarat Titans                  4363
Gujarat Lions                   3802
Lucknow Super Giants            3666
Rising Pune Supergiant          1868
Rising Pune Supergiants         1603
Kochi Tuskers Kerala            1546
Name: count, dtype: int64

In [87]:
data['Winner'].value_counts()

Winner
Mumbai Indians                 33149
Chennai Super Kings            31670
Kolkata Knight Riders          28067
Royal Challengers Bangalore    26801
Rajasthan Royals               24298
Kings XI Punjab                20162
Sunrisers Hyderabad            18495
Delhi Daredevils               15709
Delhi Capitals                  9197
Deccan Chargers                 7013
Gujarat Titans                  5562
Punjab Kings                    4619
Lucknow Super Giants            4195
Gujarat Lions                   3063
Pune Warriors                   2883
Rising Pune Supergiant          2383
Kochi Tuskers Kerala            1322
Rising Pune Supergiants         1105
Name: count, dtype: int64

In [88]:
data['Winner'].replace('Delhi Daredevils', 'Delhi Capitals', inplace=True)
data['Winner'].replace('Punjab Kings', 'Kings XI Punjab', inplace=True)

In [89]:
data['Winner'].value_counts()

Winner
Mumbai Indians                 33149
Chennai Super Kings            31670
Kolkata Knight Riders          28067
Royal Challengers Bangalore    26801
Delhi Capitals                 24906
Kings XI Punjab                24781
Rajasthan Royals               24298
Sunrisers Hyderabad            18495
Deccan Chargers                 7013
Gujarat Titans                  5562
Lucknow Super Giants            4195
Gujarat Lions                   3063
Pune Warriors                   2883
Rising Pune Supergiant          2383
Kochi Tuskers Kerala            1322
Rising Pune Supergiants         1105
Name: count, dtype: int64

In [90]:
target_columns = ['Bat First', 'Bat Second', 'Winner']
values_to_be_dropped =['Pune Warriors','Rising Pune Supergiant','Rising Pune Supergiants','Kochi Tuskers Kerala']

data = data[~data[target_columns].isin(values_to_be_dropped).any(axis=1)]

In [91]:
data['Winner'].value_counts()

Winner
Mumbai Indians                 31450
Chennai Super Kings            30438
Kolkata Knight Riders          26470
Royal Challengers Bangalore    24610
Delhi Capitals                 23476
Kings XI Punjab                23383
Rajasthan Royals               23134
Sunrisers Hyderabad            17775
Deccan Chargers                 6048
Gujarat Titans                  5562
Lucknow Super Giants            4195
Gujarat Lions                   2342
Name: count, dtype: int64

In [92]:
data['Innings'].value_counts()

Innings
1    113126
2    105757
Name: count, dtype: int64

In [93]:
data['Over'].value_counts()

Over
2     11546
1     11517
3     11415
5     11389
4     11386
6     11323
7     11293
8     11279
9     11249
10    11228
11    11146
12    11144
13    11121
14    11029
15    10929
16    10801
17    10668
18    10351
19     9684
20     8385
Name: count, dtype: int64

In [94]:
data['Ball'].value_counts()

Ball
1    36845
2    36603
3    36501
4    36457
5    36280
6    36160
0       21
7       16
Name: count, dtype: int64

In [95]:
data['Batter'].value_counts()

Batter
V Kohli         5267
S Dhawan        5116
RG Sharma       4578
DA Warner       4471
SK Raina        3910
                ...
JL Denly           1
S Lamichhane       1
Abdul Basith       1
Yash Dayal         1
C Nanda            1
Name: count, Length: 617, dtype: int64

In [96]:
data['Bowler'].value_counts()

Bowler
R Ashwin           3818
SP Narine          3591
PP Chawla          3432
Harbhajan Singh    3276
YS Chahal          3175
                   ...
D Brevis              3
SN Khan               2
DA Warner             2
YBK Jaiswal           1
AC Gilchrist          1
Name: count, Length: 488, dtype: int64

In [97]:
data['Ball'].value_counts()

Ball
1    36845
2    36603
3    36501
4    36457
5    36280
6    36160
0       21
7       16
Name: count, dtype: int64

In [98]:
data['Venue'].unique()

array(['Eden Gardens', 'De Beers Diamond Oval', 'Sharjah Cricket Stadium',
       'Wankhede Stadium', 'Feroz Shah Kotla',
       'Maharashtra Cricket Association Stadium',
       'MA Chidambaram Stadium', 'Dubai International Cricket Stadium',
       'Kingsmead', 'Dr DY Patil Sports Academy', 'SuperSport Park',
       'Sawai Mansingh Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'M Chinnaswamy Stadium', 'Rajiv Gandhi International Stadium',
       'Brabourne Stadium', 'Sheikh Zayed Stadium',
       'M.Chinnaswamy Stadium', 'Punjab Cricket Association Stadium',
       'Narendra Modi Stadium', 'Arun Jaitley Stadium',
       'Holkar Cricket Stadium', 'Saurashtra Cricket Association Stadium',
       'Punjab Cricket Association IS Bindra Stadium',
       'Sardar Patel Stadium',
       'Himachal Pradesh Cricket Association Stadium', 'Barabati Stadium',
       'Green Park', 'JSCA International Stadium Complex',
       'Zayed Cricket Stadium', 'Vidarbha Cricket Association Stadium',
       'Subrata Roy Sahara Stadium', "St George's Park",
       'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'New Wanderers Stadium', 'Newlands', 'OUTsurance Oval',
       'Buffalo Park', 'Barsapara Cricket Stadium'], dtype=object)

In [ ]:
# Standardizing Venue Names
venue_map = {
    "M.Chinnaswamy Stadium": "M Chinnaswamy Stadium",
    "Sardar Patel Stadium": "Narendra Modi Stadium",
    "Punjab Cricket Association IS Bindra Stadium": "Punjab Cricket Association Stadium",
    "Feroz Shah Kotla": "Arun Jaitley Stadium",
    "Zayed Cricket Stadium": "Sheikh Zayed Stadium",
    "De Beers Diamond Oval": "Kimberley Oval",
    "Rajiv Gandhi International Stadium": "Uppal Stadium",
    "Dr Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium": "ACA-VDCA Stadium",
    "Shaheed Veer Narayan Singh International Stadium": "Raipur International Cricket Stadium",
    "JSCA International Stadium Complex": "Ranchi Stadium",
    "Barsapara Cricket Stadium": "Assam Cricket Association Stadium"
}
data["Venue"] = data["Venue"].replace(venue_map)

In [100]:
data['Batter'].unique()

array(['RD Gaikwad', 'DP Conway', 'AM Rahane', 'S Dube', 'RA Jadeja',
       'MS Dhoni', 'N Jagadeesan', 'SP Narine', 'VR Iyer', 'N Rana',
       'JJ Roy', 'RK Singh', 'AD Russell', 'D Wiese', 'UT Yadav',
       'CV Varun', 'GC Smith', 'NV Ojha', 'SA Asnodkar', 'YK Pathan',
       'LA Carseldine', 'AS Raut', 'SK Warne', 'SM Harwood', 'M Vijay',
       'ML Hayden', 'SK Raina', 'S Badrinath', 'JDP Oram', 'RG Sharma',
       'Q de Kock', 'SA Yadav', 'SS Tiwary', 'KA Pollard', 'HH Pandya',
       'KH Pandya', 'NM Coulter-Nile', 'J Yadav', 'JJ Bumrah', 'PP Shaw',
       'S Dhawan', 'SPD Smith', 'RR Pant', 'SS Iyer', 'AR Patel',
       'SO Hetmyer', 'R Ashwin', 'LMP Simmons', 'PA Patel', 'AT Rayudu',
       'Harbhajan Singh', 'J Suchith', 'DR Smith', 'F du Plessis',
       'MEK Hussey', 'DJ Bravo', 'P Negi', 'MM Sharma', 'A Nehra',
       'G Gambhir', 'V Sehwag', 'TM Dilshan', 'MF Maharoof',
       'Shoaib Malik', 'SE Marsh', 'JR Hopes', 'Yuvraj Singh',
       'LA Pomersbach', 'DPMD Jayawardene', 'CH Gayle', 'V Kohli',
       'UBT Chand', 'DA Warner', 'Y Venugopal Rao', 'LRPL Taylor',
       'IK Pathan', 'CA Ingram', 'KMA Paul', 'R Tewatia', 'BCJ Cutting',
       'MJ McClenaghan', 'Rasikh Salam', 'Abhishek Sharma',
       'KS Williamson', 'RA Tripathi', 'AK Markram', 'N Pooran',
       'Washington Sundar', 'Shashank Singh', 'M Jansen', 'WP Saha',
       'Shubman Gill', 'DA Miller', 'A Manohar', 'Rashid Khan',
       'MA Agarwal', 'JM Bairstow', 'LS Livingstone', 'JM Sharma',
       'M Shahrukh Khan', 'OF Smith', 'Ishan Kishan', 'D Brevis',
       'Tilak Varma', 'JD Unadkat', 'M Ashwin', 'TS Mills', 'L Ronchi',
       'ST Jayasuriya', 'RV Uthappa', 'SM Pollock', 'AM Nayar',
       'MA Khote', 'BB McCullum', 'M Manhas', 'SV Samson', 'SR Watson',
       'STR Binny', 'R Bhatia', 'JP Faulkner', 'TG Southee',
       'DS Kulkarni', 'PV Tambe', 'RS Bopara', 'K Goel', 'KC Sangakkara',
       'T Kohli', 'PP Chawla', 'BJ Hodge', 'RE Levi', 'DJ Jacobs',
       'KD Karthik', 'CJ McKay', 'RP Singh', 'PP Ojha', 'MM Patel',
       'KP Pietersen', 'JC Buttler', 'D Padikkal', 'DJ Mitchell',
       'R Parag', 'TA Boult', 'TH David', 'DR Sams', 'MK Tiwary',
       'JP Duminy', 'NJ Maddinson', 'KK Nair', 'DJ Hooda', 'J Theron',
       'AC Gilchrist', 'HH Gibbs', 'AA Bilakhia', 'TL Suman',
       'Shoaib Ahmed', 'AB de Villiers', 'YBK Jaiswal', 'Dhruv Jurel',
       'MM Ali', 'JA Morkel', 'KM Jadhav', 'SN Thakur',
       'Anmolpreet Singh', 'AF Milne', 'RD Chahar', 'B Chipli',
       'W Jaffer', 'JH Kallis', 'Misbah-ul-Haq', 'R Dravid', 'MV Boucher',
       'P Kumar', 'VVS Laxman', 'Shahid Afridi', 'SB Styris', 'SB Bangar',
       'AS Yadav', 'Y Nagar', 'MJ Guptill', 'MC Henriques', 'EJG Morgan',
       'D Pretorius', 'KL Rahul', 'MK Pandey', 'E Lewis', 'A Badoni',
       'BA Stokes', 'AJ Turner', 'SE Rutherford', 'CA Pujara',
       'GJ Maxwell', 'GJ Bailey', 'R Dhawan', 'MG Johnson', 'L Balaji',
       'Sandeep Sharma', 'CA Lynn', 'M Morkel', 'M Markande',
       'C de Grandhomme', 'Mandeep Singh', 'TM Head', 'Sachin Baby',
       'S Aravind', 'YS Chahal', 'A Choudhary', 'PK Garg', 'R Shepherd',
       'B Kumar', 'Umran Malik', 'PN Mankad', 'M Vohra', 'DJ Hussey',
       'Gurkeerat Singh', 'Azhar Mahmood', 'R Sathish', 'RJ Harris',
       'P Awana', 'PJ Cummins', 'KL Nagarkoti', 'S Gopal', 'JC Archer',
       'Kartik Tyagi', 'VR Aaron', 'Shakib Al Hasan', 'Mohammad Nabi',
       'Basil Thampi', 'S Kaul', 'Mustafizur Rahman', 'MS Bisla',
       'RR Rossouw', 'SN Khan', 'HV Patel', 'MA Starc', 'MJ Lumb',
       'FY Fazal', 'AA Jhunjhunwala', 'HC Brook', 'GD Phillips',
       'Abdul Samad', 'AU Rashid', 'MP Stoinis', 'V Shankar',
       'SW Billings', 'DL Chahar', 'B Sai Sudharsan', 'SR Tendulkar',
       'DB Das', 'R McLaren', 'Iqbal Abdulla', 'MD Mishra', 'A Symonds',
       'MR Marsh', 'B Sumanth', 'WPUJC Vaas', 'R Sharma',
       'PD Collingwood', 'A Mishra', 'S Vidyut', 'SP Fleming',
       'CK Kapugedera', 'JPR Scantlebury-Searles', 'AJ Finch', 'AJ Tye',
       'BB Sran', 'Abishek Porel', 'Aman Hakim Khan', 'Kuldeep Yadav',
       'A Nortje', 'DT Christian', 'KB Arun Karthik', 'RT Ponting',
       'CH Morris', 'B Laughlin', 'OC McCoy', 'MS Wade', 'HM Amla',
       'AD Nath', 'DJG Sammy', 'KV Sharma', 'SM Curran', 'NS Naik',
       'AP Tare', 'RM Patidar', 'Fazalhaq Farooqi', 'Anureet Singh',
       'Karanveer Singh', 'Mohammed Siraj', 'DR Shorey', 'DW Steyn',
       'KW Richardson', 'AL Menaria', 'OA Shah', 'KK Cooper',
       'PC Valthaty', 'Bipul Sharma', 'Harmeet Singh', 'Sunny Singh',
       'SL Malinga', 'CJ Anderson', 'IR Jaggi', 'DB Ravi Teja',
       'I Sharma', 'A Ashish Reddy', 'GH Vihari', 'JDS Neesham',
       'CJ Jordan', 'DJ Harris', 'CL White', 'SMSM Senanayake',
       'P Simran Singh', 'Mujeeb Ur Rahman', 'Mohammed Shami',
       'DJ Thornely', 'PR Shah', 'S Chanderpaul', 'B Akhil',
       'Lalit Yadav', 'R Powell', 'Anirudh Singh', 'Jaskaran Singh',
       'AB Barath', 'S Sreesanth', 'JR Philippe', 'Navdeep Saini',
       'RN ten Doeschate', 'GB Hogg', 'CR Brathwaite', 'Z Khan',
       'SC Ganguly', 'Mohammad Hafeez', 'LR Shukla', 'AB Agarkar',
       'M Kartik', 'Anuj Rawat', 'SS Prabhudessai', 'Shahbaz Ahmed',
       'DL Vettori', 'R Vinay Kumar', 'A Mithun', 'KP Appanna',
       'A Kumble', 'Sohail Tanvir', 'M Kaif', 'M Rawat', 'SK Trivedi',
       'Mohammad Asif', 'VY Mahesh', 'GD McGrath', 'KS Bharat',
       'KA Jamieson', 'JO Holder', 'R Shukla', 'TK Curran', 'S Sohal',
       'MJ Santner', 'Salman Butt', 'A Chopra', 'T Taibu', 'AN Ghosh',
       'AD Mathews', 'JD Ryder', 'N Wadhera', 'Vishnu Vinod', 'C Green',
       'Noor Ahmad', 'AS Joseph', 'JA Richardson', 'LPC Silva',
       'AS Rajpoot', 'PBB Rajapaksa', 'Harpreet Brar',
       'Rahmanullah Gurbaz', 'PJ Sangwan', 'SD Lad', 'ER Dwivedi',
       'AD Hales', 'RA Bawa', 'TL Seifert', 'M Prasidh Krishna',
       'HF Gurney', 'DJM Short', 'K Gowtham', 'H Klaasen', 'NT Ellis',
       'IS Sodhi', 'RE van der Merwe', 'AS Roy', 'AD Mascarenhas',
       'NK Patel', 'SP Goswami', 'B Lee', 'K Rabada', 'TU Deshpande',
       'MA Wood', 'Imran Tahir', 'KC Cariappa', 'AP Dole', 'S Badree',
       'WA Mota', 'RR Powar', 'I Malhotra', 'TR Birt', 'NLTC Perera',
       'N Saini', 'BB Samantray', 'DH Yagnik', 'CM Gautam', 'FA Allen',
       'SB Joshi', 'AG Paunikar', 'A Singh', 'SW Tait', 'JM Kemp',
       'MK Lomror', 'Ankit Sharma', 'Ramandeep Singh', 'DS Lehmann',
       'D Salunkhe', 'P Dogra', 'X Thalaivan Sargunam', 'Pankaj Singh',
       'J Botha', 'MC Juneja', 'S Nadeem', 'PA Reddy', 'S Ladda',
       'DP Nannes', 'MN Samuels', 'BJ Haddin', 'RV Patel', 'KK Ahmed',
       'S Anirudha', 'CR Woakes', 'Swapnil Singh', 'K Kartikeya',
       'JP Behrendorff', 'GHS Garton', 'KR Mayers', 'SA Abbott',
       'AN Ahmed', 'AA Chavan', 'Younis Khan', 'Kamran Akmal',
       'JEC Franklin', 'HR Shokeen', 'Arshad Khan', 'BMAJ Mendis',
       'I Udana', 'LE Plunkett', 'SP Jackson', 'DJ Willey',
       'PWH de Silva', 'S Rana', 'TM Srivastava', 'Umar Gul',
       'Vijaykumar Vyshak', 'M Muralitharan', 'B Indrajith',
       'Harshit Rana', 'Akash Deep', 'JR Hazlewood', 'J Arunkumar',
       'DT Patil', 'Abdur Razzak', 'A Chandila', 'Abdul Basith',
       'SM Katich', 'AC Voges', 'SD Chitnis', 'CRD Fernando',
       'VS Yeligati', 'AUK Pathan', 'A Uniyal', 'MS Gony', 'P Sahu',
       'RJ Peterson', 'L Ablish', 'RS Sodhi', 'GC Viljoen', 'Avesh Khan',
       'S Lamichhane', 'AC Blizzard', 'YV Takawale', 'RR Raje',
       'Arshdeep Singh', 'VG Arora', 'S Kaushik', 'BR Dunk', 'AB Dinda',
       'Shivam Mavi', 'C Munro', 'Atharva Taide', 'MW Short',
       'Harpreet Singh', 'MN van Wyk', 'H Das', 'DNT Zoysa', 'BA Bhatt',
       'D Kalyankrishna', 'RR Sarwan', 'Ravi Bishnoi', 'Naveen-ul-Haq',
       'Y Prithvi Raj', 'KJ Abbott', 'MDKJ Perera', 'VH Zol',
       'CK Langeveldt', 'A Zampa', 'S Narwal', 'BJ Rohrer', 'RK Bhui',
       'LH Ferguson', 'M de Lange', 'C Sakariya', 'K Yadav', 'P Chopra',
       'T Stubbs', 'R Rampaul', 'YV Dhull', 'RR Bhatkal', 'KAJ Roach',
       'R Sanjay Yadav', 'A Mukund', 'SB Jakati', 'Yashpal Singh',
       'BAW Mendis', 'PD Salt', 'A Flintoff', 'Joginder Sharma',
       'T Thushara', 'JJ van der Wath', 'R Ninan', 'Yash Dayal',
       'Yudhvir Singh', 'RJ Quiney', 'M Ntini', 'Virat Singh',
       'MD Shanaka', 'Sanvir Singh', 'KMDN Kulasekara', 'VRV Singh',
       'U Kaul', 'B Stanlake', 'Parvez Rasool', 'DE Bollinger',
       'Sunny Gupta', 'T Banton', 'S Tyagi', 'AA Noffke', 'AB McDonald',
       'RG More', 'T Henderson', 'SS Shaikh', 'J Syed Mohammad',
       'C Nanda', 'JL Pattinson', 'BE Hendricks', 'AT Carey',
       'PVD Chameera', 'RS Gavaskar', 'SE Bond', 'C Madan',
       'DJ Muthuswami', 'HE van der Dussen', 'Mukesh Kumar',
       'MG Bracewell', 'DJ Malan', 'AG Murtaza', 'T Natarajan',
       'P Ray Barman', 'A Tomar', 'Mukesh Choudhary', 'S Sriram',
       'Sikandar Raza', 'KS Sharma', 'Kamran Khan', 'P Parameswaran',
       'D du Preez', 'Liton Das', 'YA Abdulla', 'Simarjeet Singh',
       'M Theekshana', 'Vivrant Sharma', 'R Bishnoi', 'AJ Hosein',
       'Shivam Sharma', 'A Dananjaya', 'VS Malik', 'SJ Srivastava',
       'P Dubey', 'Mashrafe Mortaza', 'SS Cottrell', 'JE Root', 'KM Asif',
       'Mohit Rathee', 'Mohsin Khan', 'Ankit Soni', 'S Randiv',
       'RP Meredith', 'JL Denly', 'F Behardien', 'GR Napier',
       'FH Edwards', 'PM Sarvesh Kumar', 'DP Vijaykumar',
       'Mohammad Ashraful', 'V Pratap Singh', 'AR Bawne', 'DR Martyn',
       'Arjun Tendulkar', 'KR Sen', 'DAJ Bracewell', 'WD Parnell',
       'Shoaib Akhtar', 'DG Nalkande', 'T Shamsi'], dtype=object)

In [101]:
# Standardizing Player Names
data["Batter"] = data["Batter"].str.strip().str.title()
data["Non Striker"] = data["Non Striker"].str.strip().str.title()
data["Bowler"] = data["Bowler"].str.strip().str.title()
data["Player Out"] = data["Player Out"].str.strip().str.title()

In [ ]:
data.dtypes #to display data-type of each column

Venue                       object
Bat First                   object
Bat Second                  object
Innings                      int64
Over                         int64
Ball                         int64
Batter                      object
Non Striker                 object
Bowler                      object
Batter Runs                  int64
Extra Runs                   int64
Runs From Ball               int64
Ball Rebowled                int64
Extra Type                  object
Wicket                       int64
Method                      object
Player Out                  object
Innings Runs                 int64
Innings Wickets              int64
Target Score                 int64
Runs to Get                float64
Balls Remaining              int64
Winner                      object
Chased Successfully          int64
Total Batter Runs            int64
Total Non Striker Runs       int64
Batter Balls Faced           int64
Non Striker Balls Faced      int64
Player Out Runs            float64
Player Out Balls Faced     float64
Bowler Runs Conceded         int64
Valid Ball                   int64
dtype: object

In [103]:
# Convert Ball Rebowled to boolean
data['Ball Rebowled'] = data['Ball Rebowled'].astype(bool)
# Convert Runs to Get to integer
data['Runs to Get'] = data['Runs to Get'].astype(int)
# Convert Player Out Runs to integer
data['Player Out Runs'] = data['Player Out Runs'].astype(int)
# Convert Player Out Balls Faced to integer
data['Player Out Balls Faced'] = data['Player Out Balls Faced'].astype(int)

In [104]:
data.head()

,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,Bowler,Batter Runs,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
0,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,1,Rd Gaikwad,Dp Conway,Ut Yadav,4,...,Chennai Super Kings,0,4,0,1,0,0,0,4,1
1,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,2,Rd Gaikwad,Dp Conway,Ut Yadav,0,...,Chennai Super Kings,0,4,0,2,0,0,0,0,1
2,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,3,Rd Gaikwad,Dp Conway,Ut Yadav,0,...,Chennai Super Kings,0,4,0,3,0,0,0,0,1
3,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,4,Rd Gaikwad,Dp Conway,Ut Yadav,0,...,Chennai Super Kings,0,4,0,4,0,0,0,0,1
4,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,5,Rd Gaikwad,Dp Conway,Ut Yadav,1,...,Chennai Super Kings,0,5,0,5,0,0,0,1,1

In [105]:
data.duplicated().sum()

np.int64(0)

In [106]:
data.isna().sum()

Venue                      0
Bat First                  0
Bat Second                 0
Innings                    0
Over                       0
Ball                       0
Batter                     0
Non Striker                0
Bowler                     0
Batter Runs                0
Extra Runs                 0
Runs From Ball             0
Ball Rebowled              0
Extra Type                 0
Wicket                     0
Method                     0
Player Out                 0
Innings Runs               0
Innings Wickets            0
Target Score               0
Runs to Get                0
Balls Remaining            0
Winner                     0
Chased Successfully        0
Total Batter Runs          0
Total Non Striker Runs     0
Batter Balls Faced         0
Non Striker Balls Faced    0
Player Out Runs            0
Player Out Balls Faced     0
Bowler Runs Conceded       0
Valid Ball                 0
dtype: int64

In [107]:
categorical_columns = data.select_dtypes(include=['object', 'category']).columns.tolist()
print(categorical_columns)

['Venue', 'Bat First', 'Bat Second', 'Batter', 'Non Striker', 'Bowler', 'Extra Type', 'Method', 'Player Out', 'Winner']

In [108]:
data['is_six'] = (data['Batter Runs'] == 6).astype(int)

In [109]:
data['Method'].unique()

array(['caught', 'bowled', 'lbw', 'stumped', 'run out',
       'caught and bowled', 'retired hurt', 'hit wicket', 'retired out',
       'obstructing the field'], dtype=object)

In [ ]:
valid_methods = ['bowled', 'caught', 'lbw', 'stumped', 'caught and bowled', 'hit wicket']
data['bowler_wickets'] = data['Method'].isin(valid_methods).astype(int)

In [111]:
data['is_dot_ball'] = (
                      (data['Runs From Ball'] == 0)
                      & (data['Extra Runs'] == 0)
                      & (data['Valid Ball'] == 1)
                    ).astype(int)

In [112]:
data.head()

,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,Bowler,Batter Runs,...,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball,is_six,bowler_wickets,is_dot_ball
0,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,1,Rd Gaikwad,Dp Conway,Ut Yadav,4,...,0,1,0,0,0,4,1,0,1,0
1,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,2,Rd Gaikwad,Dp Conway,Ut Yadav,0,...,0,2,0,0,0,0,1,0,1,1
2,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,3,Rd Gaikwad,Dp Conway,Ut Yadav,0,...,0,3,0,0,0,0,1,0,1,1
3,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,4,Rd Gaikwad,Dp Conway,Ut Yadav,0,...,0,4,0,0,0,0,1,0,1,1
4,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,5,Rd Gaikwad,Dp Conway,Ut Yadav,1,...,0,5,0,0,0,1,1,0,1,0

In [113]:
data.tail()

,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,Bowler,Batter Runs,...,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball,is_six,bowler_wickets,is_dot_ball
239688,Uppal Stadium,Delhi Capitals,Sunrisers Hyderabad,2,20,1,Yk Pathan,Ks Williamson,Dt Christian,2,...,31,9,29,0,0,2,1,0,1,0
239689,Uppal Stadium,Delhi Capitals,Sunrisers Hyderabad,2,20,2,Yk Pathan,Ks Williamson,Dt Christian,6,...,31,10,29,0,0,6,1,1,1,0
239690,Uppal Stadium,Delhi Capitals,Sunrisers Hyderabad,2,20,3,Yk Pathan,Ks Williamson,Dt Christian,4,...,31,11,29,0,0,4,1,0,1,0
239691,Uppal Stadium,Delhi Capitals,Sunrisers Hyderabad,2,20,4,Yk Pathan,Ks Williamson,Dt Christian,1,...,31,12,29,0,0,1,1,0,1,0
239692,Uppal Stadium,Delhi Capitals,Sunrisers Hyderabad,2,20,5,Ks Williamson,Yk Pathan,Dt Christian,1,...,27,30,12,0,0,1,1,0,1,0